# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/language-android/ for more details.
version: 2.1

orbs:
  node: circleci/node@x.y

executors:
  node-executor:
    docker:
      - image: circleci/node:14.17-browsers  # Node image with browsers for running tests
    working_directory: ~/ambis-auto-mobile-app

jobs:
  test:
    executor: node-executor
    environment:
      BROWSERSTACK_USERNAME: qatestingtechnol1  # BrowserStack credentials
      BROWSERSTACK_ACCESS_KEY: ubKJg1fyqyprtJMiJedy
    steps:
      - checkout  # Checkout your Bitbucket repo

      - run:
          name: Install dependencies
          command: |
            npm install  # Install project dependencies

      - run:
          name: Run execute-on-ci.sh
          command: ./execute-on-ci.sh  # Execute the script in the repository

workflows:
  version: 2
  test:
    jobs:
      - test