# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/language-android/ for more details.
version: 2.1

orbs:
  node: circleci/node@7.0.0

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20.6-browsers
  compute-engine:
    machine: true
    resource_class: amarbank/compute_sre

jobs:
  ambis-mobile-app-auto:
    executor: node-executor
    environment:
      BROWSERSTACK_USERNAME: qatestingtechnol1  # BrowserStack credentials
      BROWSERSTACK_API_KEY: ubKJg1fyqyprtJMiJedy
      FIREBASE_PROJECT_NUMBER: "594672590520" # firebase credentials
      FIREBASE_APP_ID: 1:594672590520:android:2a5c88ca5cba8e12031e4d
      
    steps:
      - checkout  # Checkout your Bitbucket repo

      - run:
          name: Showing all directory current location
          command: |
            pwd && ls -la

      - run:
          name: Install dependencies based on package.json
          command: |
            npm install
            
      - run:
          name: Install dependencies
          command: |
            npm install codeceptjs webdriverio@8.6.3 --save

      - run:
          name: Make execute-on-ci.sh executable
          command: chmod +x ./execute-on-ci.sh  # Ensure script is executable

      - run:
          name: Run execute-on-ci.sh
          command: ./execute-on-ci.sh  # Execute the script in the repository

commands:
  create-env:
      steps:
        - run:
            name: Create .env as file for environment variable
            command: |
              touch .env
              echo "BROWSERSTACK_USERNAME=$BROWSERSTACK_USERNAME" > .env
              echo "BROWSERSTACK_ACCESS_KEY=$BROWSERSTACK_ACCESS_KEY" > .env

workflows:
  version: 2.1
  test:
    jobs:
      - ambis-mobile-app-auto:
         context:
           - regressionTest
         filters:
            branches:
              only:
                - master